/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicis.interficiechat;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author dam
 */
public class ClassMain extends javax.swing.JFrame {

    /**
     * Creates new form ClassMain
     */
    public ClassMain() {
        initComponents();
        inicialitzarIcons();
    }

    /**
     *
     */
    private void inicialitzarIcons() {
        ImageIcon iconoClientAModificar = new ImageIcon("src\\main\\java\\img\\iconoClient.png");
        ImageIcon iconoServidorAModificar = new ImageIcon("src\\main\\java\\img\\iconoServidor.png");
        ImageIcon iconoPrincipalAModificar = new ImageIcon("src\\main\\java\\img\\logoXat.png");
        
        Image iconoServidorModificat = iconoServidorAModificar.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        Image iconoClientModificat = iconoClientAModificar.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        Image iconoPrincipalModificat = iconoPrincipalAModificar.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);

        ImageIcon iconoServidor = new ImageIcon(iconoServidorModificat);
        ImageIcon iconoClients = new ImageIcon(iconoClientModificat);
        ImageIcon iconoPrincipal = new ImageIcon(iconoPrincipalModificat);
        
        this.jButton3.setIcon(iconoServidor);
        this.jButton4.setIcon(iconoClients);
        this.jLabel2.setIcon(iconoPrincipal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        partDreta = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        main = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        partEsquerra = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGeneral.setLayout(new java.awt.BorderLayout());

        header.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("jLabel1");
        header.add(jLabel1, new java.awt.GridBagConstraints());

        panelGeneral.add(header, java.awt.BorderLayout.PAGE_START);

        partDreta.setLayout(new java.awt.GridLayout());

        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        partDreta.add(jButton3);

        panelGeneral.add(partDreta, java.awt.BorderLayout.LINE_END);

        main.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("jLabel2");
        main.add(jLabel2, new java.awt.GridBagConstraints());

        panelGeneral.add(main, java.awt.BorderLayout.CENTER);

        partEsquerra.setLayout(new java.awt.GridBagLayout());

        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(true);
        partEsquerra.add(jButton4, new java.awt.GridBagConstraints());

        panelGeneral.add(partEsquerra, java.awt.BorderLayout.LINE_START);

        footer.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("jButton1");
        footer.add(jButton1, new java.awt.GridBagConstraints());

        jButton2.setText("jButton2");
        footer.add(jButton2, new java.awt.GridBagConstraints());

        panelGeneral.add(footer, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.out.println("Entrem aqui...");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel partDreta;
    private javax.swing.JPanel partEsquerra;
    // End of variables declaration//GEN-END:variables
}
