package exercicis.interficiechat;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author David Boix Sanchez i Oleh Plechiy Tupis Andriyovech
 */
public class ClassMain extends javax.swing.JFrame {

    /**
     * Creates new form ClassMain
     */
    public ClassMain() {
        this.initComponents();
        this.inicialitzarIcons();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     *
     */
    private void inicialitzarIcons() {
        //ImageIcon iconoClientAModificar = new ImageIcon("src\\main\\java\\img\\logoXat.png");
        ImageIcon iconoClientAModificar = new ImageIcon(getClass().getResource("/logoXat.png"));
        ImageIcon iconoServidorAModificar = new ImageIcon("src\\main\\java\\img\\iconoServidor.png");
        //ImageIcon iconoPrincipalAModificar = new ImageIcon("src\\main\\java\\img\\logoXat.png");

        Image iconoServidorModificat = iconoServidorAModificar.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        Image iconoClientModificat = iconoClientAModificar.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        //Image iconoPrincipalModificat = iconoPrincipalAModificar.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);

        ImageIcon iconoServidor = new ImageIcon(iconoServidorModificat);
        ImageIcon iconoClients = new ImageIcon(iconoClientModificat);
        //ImageIcon iconoPrincipal = new ImageIcon(iconoPrincipalModificat);

        this.botoServidor.setIcon(iconoServidor);
        this.botoClient.setIcon(iconoClients);
        //this.jLabel2.setIcon(iconoPrincipal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelGeneral = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        botoClient = new javax.swing.JButton();
        botoServidor = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        accedirClient = new javax.swing.JButton();
        accedirServidor = new javax.swing.JButton();
        menuGeneral = new javax.swing.JMenuBar();
        menuNavegacio = new javax.swing.JMenu();
        opcioServidor = new javax.swing.JMenuItem();
        opcioClient = new javax.swing.JMenuItem();
        menuSortir = new javax.swing.JMenu();
        opcioSortir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGeneral.setLayout(new java.awt.BorderLayout());

        header.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("CostaXat");
        header.add(jLabel1, new java.awt.GridBagConstraints());

        panelGeneral.add(header, java.awt.BorderLayout.PAGE_START);

        main.setLayout(new java.awt.GridBagLayout());

        botoClient.setBorder(null);
        botoClient.setContentAreaFilled(false);
        botoClient.setOpaque(true);
        botoClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoClientActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 100);
        main.add(botoClient, gridBagConstraints);

        botoServidor.setBorder(null);
        botoServidor.setContentAreaFilled(false);
        botoServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoServidorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 100);
        main.add(botoServidor, gridBagConstraints);

        panelGeneral.add(main, java.awt.BorderLayout.CENTER);

        footer.setLayout(new java.awt.GridBagLayout());

        accedirClient.setText("Client");
        accedirClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accedirClientActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        footer.add(accedirClient, gridBagConstraints);

        accedirServidor.setText("Servidor");
        accedirServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accedirServidorActionPerformed(evt);
            }
        });
        footer.add(accedirServidor, new java.awt.GridBagConstraints());

        panelGeneral.add(footer, java.awt.BorderLayout.PAGE_END);

        menuGeneral.setBackground(new java.awt.Color(203, 219, 242));
        menuGeneral.setOpaque(true);

        menuNavegacio.setText("Navegació");

        opcioServidor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcioServidor.setBackground(new java.awt.Color(203, 219, 242));
        opcioServidor.setText("Obrir Servidor");
        opcioServidor.setOpaque(true);
        opcioServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcioServidorActionPerformed(evt);
            }
        });
        menuNavegacio.add(opcioServidor);

        opcioClient.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcioClient.setBackground(new java.awt.Color(203, 219, 242));
        opcioClient.setText("Obrir Client");
        opcioClient.setOpaque(true);
        opcioClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcioClientActionPerformed(evt);
            }
        });
        menuNavegacio.add(opcioClient);

        menuGeneral.add(menuNavegacio);

        menuSortir.setText("Sortir");

        opcioSortir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcioSortir.setBackground(new java.awt.Color(203, 219, 242));
        opcioSortir.setText("Sortir");
        opcioSortir.setOpaque(true);
        opcioSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcioSortirActionPerformed(evt);
            }
        });
        menuSortir.add(opcioSortir);

        menuGeneral.add(menuSortir);

        setJMenuBar(menuGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Event creat per poder mostrar la interficie grafica que servira per poder
     * aixecar el servidor,es a dir, encendre el servidor.
     *
     * @param evt
     */
    private void botoServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoServidorActionPerformed
        IniciServidor serv = new IniciServidor();
        this.mostrarInterficie(serv);
        this.tancarFinestra();
        /**
         * TODO: En aquest moment ho deixarem comentat perque estem preparant la
         * interficie
         *
         * serv.setExtendedState(MAXIMIZED_BOTH);
         */

    }//GEN-LAST:event_botoServidorActionPerformed
    /**
     * Event creat per a que quan es pulsi el boto del client per poder
     * inicialitzar.
     *
     * @param evt
     */
    private void botoClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoClientActionPerformed
        VistaPrincipal vp = new VistaPrincipal();
        this.mostrarInterficie(vp);
        this.tancarFinestra();
        /**
         * TODO: En aquest moment ho deixarem comentat perque estem preparant la
         * interficie
         *
         */
        vp.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_botoClientActionPerformed
    private void opcioServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcioServidorActionPerformed
        IniciServidor is = new IniciServidor();
        this.mostrarInterficie(is);
        this.tancarFinestra();
    }//GEN-LAST:event_opcioServidorActionPerformed
    /**
     * Event creat per poder inicialitzar una accio en concret que nosaltres
     * especificarem.
     *
     * @param evt
     */
    private void opcioClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcioClientActionPerformed
        VistaPrincipal vp = new VistaPrincipal();
        this.mostrarInterficie(vp);
        this.tancarFinestra();
    }//GEN-LAST:event_opcioClientActionPerformed

    private void opcioSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcioSortirActionPerformed
        this.dispose();
    }//GEN-LAST:event_opcioSortirActionPerformed

    private void accedirClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accedirClientActionPerformed
        VistaPrincipal vp = new VistaPrincipal();
        this.mostrarInterficie(vp);
        this.tancarFinestra();
    }//GEN-LAST:event_accedirClientActionPerformed

    private void accedirServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accedirServidorActionPerformed
        IniciServidor is = new IniciServidor();
        this.mostrarInterficie(is);
        this.tancarFinestra();
    }//GEN-LAST:event_accedirServidorActionPerformed

    private void tancarFinestra() {
        this.setVisible(false);
    }

    /**
     * Funcio creada per poder mostrar una interficie grafica que nosaltres
     * passarem per parametres.
     *
     * @param jf La interficie que volem mostrar per pantalla.
     */
    private void mostrarInterficie(JFrame jframe) {
        jframe.setVisible(true);
        jframe.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accedirClient;
    private javax.swing.JButton accedirServidor;
    private javax.swing.JButton botoClient;
    private javax.swing.JButton botoServidor;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel main;
    private javax.swing.JMenuBar menuGeneral;
    private javax.swing.JMenu menuNavegacio;
    private javax.swing.JMenu menuSortir;
    private javax.swing.JMenuItem opcioClient;
    private javax.swing.JMenuItem opcioServidor;
    private javax.swing.JMenuItem opcioSortir;
    private javax.swing.JPanel panelGeneral;
    // End of variables declaration//GEN-END:variables
}
