package exercicis.interficiechat;

import java.text.SimpleDateFormat;
import java.util.Date;
import funcionsbbdd.CrudMONGO;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author David Boix Sanchez i Oleh Plechiy Tupis Andriyovech
 * @version 1.0
 */
public class GetMissatgeData extends javax.swing.JFrame {

    /**
     * Creates new form GetMissatgeData
     */
    public GetMissatgeData() {
        initComponents();
        this.inicialitzarIconos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        dataElegida = new com.toedter.calendar.JDateChooser();
        botoConsulta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        menuGeneral = new javax.swing.JMenuBar();
        menuNavegacio = new javax.swing.JMenu();
        menuOpcioVistaPrincipal = new javax.swing.JMenuItem();
        menuOpcioLogin = new javax.swing.JMenuItem();
        menuSortir = new javax.swing.JMenu();
        menuOpcioSortir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mostrar missatges per data");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(203, 219, 242));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mostrar missatges");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(203, 219, 242));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        textArea.setEditable(false);
        textArea.setMinimumSize(new java.awt.Dimension(26, 20));
        textArea.setPreferredSize(new java.awt.Dimension(400, 220));
        jScrollPane1.setViewportView(textArea);

        jPanel4.add(jScrollPane1, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(203, 219, 242));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        dataElegida.setOpaque(false);
        dataElegida.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 45);
        jPanel3.add(dataElegida, gridBagConstraints);

        botoConsulta.setBackground(new java.awt.Color(125, 165, 221));
        botoConsulta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botoConsulta.setText("Consultar");
        botoConsulta.setToolTipText("");
        botoConsulta.setMaximumSize(new java.awt.Dimension(150, 26));
        botoConsulta.setMinimumSize(new java.awt.Dimension(150, 26));
        botoConsulta.setPreferredSize(new java.awt.Dimension(120, 35));
        botoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoConsultaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel3.add(botoConsulta, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Elegeix una data: ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel2, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        menuGeneral.setBackground(new java.awt.Color(203, 219, 242));
        menuGeneral.setOpaque(true);

        menuNavegacio.setText("Navegació");

        menuOpcioVistaPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuOpcioVistaPrincipal.setBackground(new java.awt.Color(203, 219, 242));
        menuOpcioVistaPrincipal.setText("Vista Principal");
        menuOpcioVistaPrincipal.setOpaque(true);
        menuOpcioVistaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcioVistaPrincipalActionPerformed(evt);
            }
        });
        menuNavegacio.add(menuOpcioVistaPrincipal);

        menuOpcioLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuOpcioLogin.setBackground(new java.awt.Color(203, 219, 242));
        menuOpcioLogin.setText("Inici Sessió");
        menuOpcioLogin.setOpaque(true);
        menuOpcioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcioLoginActionPerformed(evt);
            }
        });
        menuNavegacio.add(menuOpcioLogin);

        menuGeneral.add(menuNavegacio);

        menuSortir.setText("Sortir");

        menuOpcioSortir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuOpcioSortir.setBackground(new java.awt.Color(203, 219, 242));
        menuOpcioSortir.setText("Sortir");
        menuOpcioSortir.setOpaque(true);
        menuOpcioSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcioSortirActionPerformed(evt);
            }
        });
        menuSortir.add(menuOpcioSortir);

        menuGeneral.add(menuSortir);

        setJMenuBar(menuGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Funcio realitzada per poder fer la consulta que farem per poder mostrar
     * TOTS els missatges que es troben en aquell moment en la base de dades
     * MongoDB passant per parametres la data.
     *
     * @param evt Event generat per poder activar la funcio a traves del ratoli
     * o teclat.F
     */
    private void botoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoConsultaActionPerformed
        this.netejarTextArea();
        String data = this.tractarDataJCalendar();
        CrudMONGO cm = new CrudMONGO("57.129.5.24", 27017, "grup1", "gat123", "comptes");
        cm.setNomColeccio("missatges");
        if (data != null) {
            cm.getMsgData(data, this.textArea);
        } else {
            System.out.println("La data es NULL!");
        }
    }//GEN-LAST:event_botoConsultaActionPerformed

    private void menuOpcioVistaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcioVistaPrincipalActionPerformed
        VistaPrincipal vistaPrincipal = new VistaPrincipal();
        this.mostrarFinestra(vistaPrincipal);
        this.tancarFinestraActual();
    }//GEN-LAST:event_menuOpcioVistaPrincipalActionPerformed

    private void menuOpcioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcioLoginActionPerformed
        Login login = new Login();
        this.mostrarFinestra(login);
        this.tancarFinestraActual();
    }//GEN-LAST:event_menuOpcioLoginActionPerformed

    private void menuOpcioSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcioSortirActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuOpcioSortirActionPerformed
    /**
     * Funcio desenvolupada per poder realitzar l'operacio pertinent que es
     * mostrar la finestra en questio que li passarem per parametres.
     *
     *
     * @param jframe JFrame que li passarem per obrir la finestra en questio.
     */
    private void mostrarFinestra(JFrame jframe) {
        jframe.setVisible(true);
        jframe.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * Funcio que utilitzarem per poder tancar la finestra de la interficie
     * grafica de Registre amb la qual estem treballant.
     */
    private void tancarFinestraActual() {
        this.setVisible(false);
    }

    /**
     * Funcio realitzada per poder tractar la data que rebem del component
     * JCalendar amb el format espanyol, es a dir, dia/mes/any ja que en la base
     * de dades ho guardem de aquesta manera.
     *
     * @return En cas de que la data s'hagui formatejat correctament enviarem la
     * data formatejada, en cas contrari, retornara NULL i no podrem fer la
     * consulta correctament.
     */
    private String tractarDataJCalendar() {
        Date data = this.dataElegida.getDate();

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String formattedDate = dateFormat.format(data);
        if (formattedDate != null) {
            return formattedDate;
        }
        return null;
    }

    /**
     * Funcio creada per poder inicialitzar les icones que apareixeran en la
     * interficie grafica que es visualitzara
     */
    private void inicialitzarIconos() {
        ImageIcon iconoBuscarAModificar = new ImageIcon(getClass().getResource("/iconoBuscarBD.png"));
        Image iconoBuscarModificat = iconoBuscarAModificar.getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH);
        ImageIcon iconoBuscar = new ImageIcon(iconoBuscarModificat);
        this.botoConsulta.setIcon(iconoBuscar);
    }

    private void netejarTextArea() {
        if (this.textArea.getText().length() > 0) {
            this.textArea.setText(null);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetMissatgeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetMissatgeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetMissatgeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetMissatgeData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetMissatgeData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoConsulta;
    private com.toedter.calendar.JDateChooser dataElegida;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuGeneral;
    private javax.swing.JMenu menuNavegacio;
    private javax.swing.JMenuItem menuOpcioLogin;
    private javax.swing.JMenuItem menuOpcioSortir;
    private javax.swing.JMenuItem menuOpcioVistaPrincipal;
    private javax.swing.JMenu menuSortir;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
