package exercicis.interficiechat;

import encriptacio.Servidor;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author David Boix Sanchez
 *
 * TODO: Aquesta interficie l'haurem de realitzar utilitzant un JavaBean, es a
 * dir, realitzarem un component personalitzat per poder aixecar el servidor amb
 * la IP que nosaltres vulguem i que en tot cas, aquest servidor existeixi sino
 * tota connexio que vulguem realitzar, no es fara correctament.
 */
public class IniciServidor extends javax.swing.JFrame {

    /**
     * Creates new form IniciServidor
     */
    public IniciServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        inputServidor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        menuGeneral = new javax.swing.JMenuBar();
        menuNavegacio = new javax.swing.JMenu();
        menuOpcioVistaPrincipal = new javax.swing.JMenuItem();
        menuOpcioLogin = new javax.swing.JMenuItem();
        menuSortir = new javax.swing.JMenu();
        menuOpcioSortir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(203, 219, 242));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel1.setText("Creació del servidor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        jPanel2.add(jLabel1, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(203, 219, 242));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(125, 165, 221));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Inici Servidor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(203, 219, 242));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(203, 219, 242));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 203, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel6.setBackground(new java.awt.Color(203, 219, 242));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        inputServidor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputServidor.setMinimumSize(new java.awt.Dimension(150, 22));
        inputServidor.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel6.add(inputServidor, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("IP Servidor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 22, 0);
        jPanel6.add(jLabel2, gridBagConstraints);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        menuGeneral.setBackground(new java.awt.Color(203, 219, 242));
        menuGeneral.setOpaque(true);

        menuNavegacio.setText("Navegació");

        menuOpcioVistaPrincipal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuOpcioVistaPrincipal.setBackground(new java.awt.Color(203, 219, 242));
        menuOpcioVistaPrincipal.setText("Vista Principal");
        menuOpcioVistaPrincipal.setOpaque(true);
        menuOpcioVistaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcioVistaPrincipalActionPerformed(evt);
            }
        });
        menuNavegacio.add(menuOpcioVistaPrincipal);

        menuOpcioLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuOpcioLogin.setBackground(new java.awt.Color(203, 219, 242));
        menuOpcioLogin.setText("Inici Sessió");
        menuOpcioLogin.setOpaque(true);
        menuOpcioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcioLoginActionPerformed(evt);
            }
        });
        menuNavegacio.add(menuOpcioLogin);

        menuGeneral.add(menuNavegacio);

        menuSortir.setText("Sortir");

        menuOpcioSortir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuOpcioSortir.setBackground(new java.awt.Color(203, 219, 242));
        menuOpcioSortir.setText("Sortir");
        menuOpcioSortir.setOpaque(true);
        menuOpcioSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcioSortirActionPerformed(evt);
            }
        });
        menuSortir.add(menuOpcioSortir);

        menuGeneral.add(menuSortir);

        setJMenuBar(menuGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Funcio desenvolupada per poder inicialitzar el servidor amb una IP
     * definida per el usuari.
     *
     * @param evt Event que li passem per parametres que activara la funcio ja
     * sigui utilitzant el ratoli o el teclat.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String ipServidor = this.inputServidor.getText();
        String[] unicaOpcio = {"Acceptar"};
        String titol = "Escriu una IP per al servidor";

        if (!ipServidor.isEmpty()) {
//            new Thread(new Runnable() {
//                @Override
//                public void run() {
//                    Servidor server = new Servidor();
//                    server.iniciServidor(ipServidor);
//                }
//            }).start();
//            Servidor server = new Servidor();
//            server.iniciServidor(ipServidor);
            this.iniciClient(ipServidor);
            this.dispose();
        } else {
            System.out.println("No pot quedar buit!");

            Icon imatge = new ImageIcon(getClass().getResource("/cross.png"));
            String missatgeErroni = "IP no pot estar buida";
            this.missatgeServidorErroni(unicaOpcio, missatgeErroni, titol, imatge);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuOpcioVistaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcioVistaPrincipalActionPerformed
        VistaPrincipal vistaPrincipal = new VistaPrincipal();
        this.mostrarFinestra(vistaPrincipal);
        this.tancarFinestraActual();
    }//GEN-LAST:event_menuOpcioVistaPrincipalActionPerformed

    private void menuOpcioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcioLoginActionPerformed
        Login login = new Login();
        this.mostrarFinestra(login);
        this.tancarFinestraActual();
    }//GEN-LAST:event_menuOpcioLoginActionPerformed

    private void menuOpcioSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcioSortirActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_menuOpcioSortirActionPerformed
    /**
     * Funcio desenvolupada per poder realitzar l'operacio pertinent que es
     * mostrar la finestra en questio que li passarem per parametres.
     *
     *
     * @param jframe JFrame que li passarem per obrir la finestra en questio.
     */
    private void mostrarFinestra(JFrame jframe) {
        jframe.setVisible(true);
        jframe.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * Funcio que utilitzarem per poder tancar la finestra de la interficie
     * grafica de Registre amb la qual estem treballant.
     */
    private void tancarFinestraActual() {
        this.setVisible(false);
    }
    /**
     * Funcio realitzada per poder mostrar la interficie grafica on el client
     * podra elegir entre iniciar sessio o registrar-se en el nostre sistema
     * gestor de base de dades.
     */
    private void iniciClient(String ipServidor) {
        VistaPrincipal vp = new VistaPrincipal(ipServidor);
        vp.setVisible(true);
        this.setVisible(false);
    }

    /**
     * Funcio desenvolupada per poder mostrar un JOptionPane personalitzat.
     *
     * @param jop Objecte JOptionPane que farem servir per mostrar un dialog.
     * @param opcions Les diferentes opcions de seleccio que podra elegir el
     * usuari.
     * @return Retornara l'opcio seleccionada, ja sigui un 1 per quan sigui
     * 'Aceptar' i un 0 una opcio diferent.
     */
    private int missatgeIniciServidor(JOptionPane jop, String[] opcions) {

        int opcioSeleccionada = jop.showOptionDialog(
                null,
                "Vols iniciar el servidor?",
                "Inici servidor",
                jop.DEFAULT_OPTION,
                jop.WARNING_MESSAGE,
                null,
                opcions,
                opcions[0]
        );

        return opcioSeleccionada;
    }

    /**
     *
     * Funcio desenvolupada per poder mostrar un JOptionPane personalitzat.
     *
     * @param jop Objecte JOptionPane que farem servir per mostrar un dialog.
     * @param opcions Les diferentes opcions de seleccio que podra elegir el
     * usuari.
     */
    private boolean missatgeServidorErroni(String[] opcions, String missatge, String titol, Icon icon) {
        JOptionPane jop = new JOptionPane();

        boolean confirmacio = false;
        int opcioSeleccionada = jop.showOptionDialog(
                null,
                missatge,
                titol,
                jop.DEFAULT_OPTION,
                jop.WARNING_MESSAGE,
                icon,
                opcions,
                opcions[0]
        );

        if (opcioSeleccionada < 0) {
            return confirmacio = true;
        }

        return confirmacio;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputServidor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JMenuBar menuGeneral;
    private javax.swing.JMenu menuNavegacio;
    private javax.swing.JMenuItem menuOpcioLogin;
    private javax.swing.JMenuItem menuOpcioSortir;
    private javax.swing.JMenuItem menuOpcioVistaPrincipal;
    private javax.swing.JMenu menuSortir;
    // End of variables declaration//GEN-END:variables
}
