package exercicis.interficiechat;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author David Boix Sanchez i
 * @version 1.0
 */
public class InterficieXat extends javax.swing.JFrame {

    /**
     * Creates new form InterficieXat
     */
    public InterficieXat() {
        initComponents();
        inicialitzarInputs();
        inicialitzarIconos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        vistaGeneral = new javax.swing.JPanel();
        headerVista = new javax.swing.JPanel();
        botoXatPrivat = new javax.swing.JButton();
        botoXatGrupal = new javax.swing.JButton();
        titolXat = new javax.swing.JLabel();
        llistatVista = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        mainVista = new javax.swing.JPanel();
        espaiControlMissatge = new javax.swing.JPanel();
        botoSetttings = new javax.swing.JButton();
        botoEnviarMsg = new javax.swing.JButton();
        inputMsg = new componentsPersonalitzats.JTextFieldPersonalitzat();
        espaiMissatges = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMissatge = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vistaGeneral.setLayout(new java.awt.BorderLayout());

        headerVista.setLayout(new java.awt.GridBagLayout());

        botoXatPrivat.setToolTipText("Boto que ens serveix per enviar missatges per privat");
        headerVista.add(botoXatPrivat, new java.awt.GridBagConstraints());

        botoXatGrupal.setToolTipText("Boto que ens serveix per enviar missatges per al grup general");
        headerVista.add(botoXatGrupal, new java.awt.GridBagConstraints());

        titolXat.setText("COSTAXAT");
        titolXat.setToolTipText("Titol de la nostra aplicacio de missatgeria");
        headerVista.add(titolXat, new java.awt.GridBagConstraints());

        vistaGeneral.add(headerVista, java.awt.BorderLayout.PAGE_START);

        llistatVista.setLayout(new java.awt.BorderLayout());

        jButton3.setText("Client 1");
        llistatVista.add(jButton3, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Llistat usuaris connectats");
        llistatVista.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jButton5.setText("Client 2");
        llistatVista.add(jButton5, java.awt.BorderLayout.PAGE_END);

        vistaGeneral.add(llistatVista, java.awt.BorderLayout.LINE_START);

        mainVista.setLayout(new java.awt.BorderLayout());

        espaiControlMissatge.setToolTipText("");
        espaiControlMissatge.setLayout(new java.awt.GridBagLayout());

        botoSetttings.setToolTipText("Boto que no te cap funcio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        espaiControlMissatge.add(botoSetttings, gridBagConstraints);

        botoEnviarMsg.setText("Enviar ");
        botoEnviarMsg.setToolTipText("Boto que serveix per enviar missatges al xat");
        botoEnviarMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoEnviarMsgActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        espaiControlMissatge.add(botoEnviarMsg, gridBagConstraints);

        inputMsg.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        espaiControlMissatge.add(inputMsg, gridBagConstraints);

        mainVista.add(espaiControlMissatge, java.awt.BorderLayout.PAGE_END);

        espaiMissatges.setLayout(new java.awt.BorderLayout());

        textAreaMissatge.setColumns(20);
        textAreaMissatge.setRows(5);
        textAreaMissatge.setToolTipText("Espai on apareixeran els missatges que enviaran els usuaris conectats al xat");
        jScrollPane1.setViewportView(textAreaMissatge);

        espaiMissatges.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        mainVista.add(espaiMissatges, java.awt.BorderLayout.CENTER);

        vistaGeneral.add(mainVista, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * 
     * @param evt 
     */
    private void botoEnviarMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoEnviarMsgActionPerformed
        
    }//GEN-LAST:event_botoEnviarMsgActionPerformed
    /**
     * Funcio creada per inicialitzar el JTextField amb un missatge per defecte
     * per a que el usuari sapigui on ha de escriure un missatge que enviara per
     * el xat.
     */
    private void inicialitzarInputs() {
        this.inputMsg.setPlaceHolder("Escriu el teu missatge...");
        this.inputMsg.setText(this.inputMsg.getPlaceHolder());
    }

    /**
     * Funcio creada per poder inicialitzar les icones que apareixeran en la
     * interficie grafica que es visualitzara
     */
    private void inicialitzarIconos() {
        
        ImageIcon iconoXatPrivatAModificar = new ImageIcon("src\\main\\java\\img\\iconoXatPrivat.png");
        ImageIcon iconoXatGrupalAModificar = new ImageIcon("src\\main\\java\\img\\iconoXatGrupal.png");
        ImageIcon iconoSettingAModificar = new ImageIcon("src\\main\\java\\img\\iconoSettings.png");
        ImageIcon iconoEnviarModificar = new ImageIcon("src\\main\\java\\img\\iconoEnviar.png");
        
        Image iconoXatPrivatModificat = iconoXatPrivatAModificar.getImage().getScaledInstance(17, 17, Image.SCALE_SMOOTH);
        Image iconoXatGrupalModificat = iconoXatGrupalAModificar.getImage().getScaledInstance(17, 17, Image.SCALE_SMOOTH);
        Image iconoSettingsModificat = iconoSettingAModificar.getImage().getScaledInstance(17, 17, Image.SCALE_SMOOTH);
        Image iconoEnviarModificat = iconoEnviarModificar.getImage().getScaledInstance(17, 17, Image.SCALE_SMOOTH);
        
        ImageIcon iconoXatPrivat = new ImageIcon(iconoXatPrivatModificat);
        ImageIcon iconoXatGrupal = new ImageIcon(iconoXatGrupalModificat);
        ImageIcon iconoSettings = new ImageIcon(iconoSettingsModificat);
        ImageIcon iconoEnviar = new ImageIcon(iconoEnviarModificat);
        
        this.botoXatPrivat.setIcon(iconoXatPrivat);
        this.botoXatGrupal.setIcon(iconoXatGrupal);
        this.botoSetttings.setIcon(iconoSettings);
        this.botoEnviarMsg.setIcon(iconoEnviar);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterficieXat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterficieXat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterficieXat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterficieXat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterficieXat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoEnviarMsg;
    private javax.swing.JButton botoSetttings;
    private javax.swing.JButton botoXatGrupal;
    private javax.swing.JButton botoXatPrivat;
    private javax.swing.JPanel espaiControlMissatge;
    private javax.swing.JPanel espaiMissatges;
    private javax.swing.JPanel headerVista;
    private componentsPersonalitzats.JTextFieldPersonalitzat inputMsg;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel llistatVista;
    private javax.swing.JPanel mainVista;
    private javax.swing.JTextArea textAreaMissatge;
    private javax.swing.JLabel titolXat;
    private javax.swing.JPanel vistaGeneral;
    // End of variables declaration//GEN-END:variables
}
