package exercicis.interficiechat;

import java.awt.Image;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ImageIcon;

/**
 *
 * @author David Boix Sanchez
 * @version 1.0
 */
public class InterficieXatProvisional extends javax.swing.JFrame {

    /**
     * TODO: Variable global que sera provisional
     */
    String resFinal = "";

    /**
     * Creates new form InterficieXatProvisional
     */
    public InterficieXatProvisional() {
        initComponents();
        inicialitzarInputs();
        inicialitzarIconos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        inputMsg = new componentsPersonalitzats.JTextFieldPersonalitzat();
        botoSettings = new javax.swing.JButton();
        botoEnviarMsg = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        botoXatGrupal = new javax.swing.JButton();
        botoXatPrivat = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        textLlistatUsuarisConectats = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMissatge = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        inputMsg.setToolTipText("");
        jPanel2.add(inputMsg, new java.awt.GridBagConstraints());

        botoSettings.setBackground(new java.awt.Color(125, 165, 221));
        botoSettings.setToolTipText("Boto que no te cap funcio");
        jPanel2.add(botoSettings, new java.awt.GridBagConstraints());

        botoEnviarMsg.setBackground(new java.awt.Color(125, 165, 221));
        botoEnviarMsg.setText("Enviar");
        botoEnviarMsg.setToolTipText("Botó que serveix per enviar missatges al xat.");
        botoEnviarMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoEnviarMsgActionPerformed(evt);
            }
        });
        jPanel2.add(botoEnviarMsg, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridBagLayout());
        jPanel5.add(botoXatGrupal, new java.awt.GridBagConstraints());
        jPanel5.add(botoXatPrivat, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COSTAXAT (NOM PROVISIONAL)");
        jPanel7.add(jLabel1);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        textLlistatUsuarisConectats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLlistatUsuarisConectats.setText("Llistat usuaris connectats");
        jPanel8.add(textLlistatUsuarisConectats);

        jPanel4.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jButton4.setText("Client 1");
        jPanel9.add(jButton4, new java.awt.GridBagConstraints());

        jButton3.setText("Client 2");
        jPanel9.add(jButton3, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jPanel1.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        textAreaMissatge.setColumns(20);
        textAreaMissatge.setRows(5);
        jScrollPane1.setViewportView(textAreaMissatge);

        jPanel6.add(jScrollPane1);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoEnviarMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoEnviarMsgActionPerformed
        String msg = this.inputMsg.getText();
        if (msg.isEmpty()) {
            System.out.println("NO pots enviar un missatge en blanc!");
            return;
        }

        if (!msg.isEmpty()) {
            String missatge = this.textAreaMissatge.getText();
            ArrayList<String> arrayListMsg = new ArrayList<>();
            arrayListMsg.add(msg);
            for (String misg : arrayListMsg) {
                resFinal += misg;
            }
            String dataActual = getData();
            String horaActual = getTemps();
            this.textAreaMissatge.setText("[" + dataActual + " || " + horaActual + "]: " + msg);
            this.inputMsg.setText(null);
        }
    }//GEN-LAST:event_botoEnviarMsgActionPerformed

    /**
     * Funcio creada per inicialitzar el JTextField amb un missatge per defecte
     * per a que el usuari sapigui on ha de escriure un missatge que enviara per
     * el xat.
     */
    private void inicialitzarInputs() {
        this.inputMsg.setPlaceHolder("Escriu el teu missatge...");
        this.inputMsg.setText(this.inputMsg.getPlaceHolder());
    }

    /**
     * Funcio desenvolupada per poder retornar la data la qual ens trobem en
     * aquell moment en format cadena de text
     *
     * @return La data de avui en format cadena de text.
     */
    private String getData() {
        Calendar cal = Calendar.getInstance();
        int dia = cal.get(Calendar.DAY_OF_MONTH);
        int mes = cal.get(Calendar.MONTH) + 1;
        int any = cal.get(Calendar.YEAR);
        String data = dia + "/" + mes + "/" + any;

        if (!data.isEmpty()) {
            return data;
        }

        return "";
    }

    /**
     * Funcio desenvolupada per obtenir la hora, minuts i segons actuals en el
     * moment que fem la crida de la funcio
     *
     * @return Hora, Minuts i Segons com una cadena de text.
     */
    private String getTemps() {
        LocalTime myObj = LocalTime.now();
        String hora = tractarTemps(myObj.getHour());
        String minuts = tractarTemps(myObj.getMinute());
        String segons = tractarTemps(myObj.getSecond());
        String temps = hora + ":" + minuts + ":" + segons;
        if (!temps.isEmpty()) {
            return temps;
        }
        return "";
    }

    /**
     * Funcio desenvolupada per poder passar tipus enters a tipus cadena de text
     * TODO: Possible canvi de nom de la funcio
     *
     * @param temps El valor enter que volem canviar a una cadena de text.
     * @return El valor enter que hem passat per parametres convertit a cadena
     * de text
     */
    private String tractarTemps(int temps) {
        String tempsActual = String.valueOf(temps);
        return tempsActual;
    }

    /**
     * Funcio creada per poder inicialitzar les icones que apareixeran en la
     * interficie grafica que es visualitzara
     */
    private void inicialitzarIconos() {

        ImageIcon iconoXatPrivatAModificar = new ImageIcon("src\\main\\java\\img\\iconoXatPrivat.png");
        ImageIcon iconoXatGrupalAModificar = new ImageIcon("src\\main\\java\\img\\iconoXatGrupal.png");
        ImageIcon iconoSettingAModificar = new ImageIcon("src\\main\\java\\img\\iconoSettings.png");
        ImageIcon iconoEnviarModificar = new ImageIcon("src\\main\\java\\img\\iconoEnviar.png");

        Image iconoXatPrivatModificat = iconoXatPrivatAModificar.getImage().getScaledInstance(17, 17, Image.SCALE_SMOOTH);
        Image iconoXatGrupalModificat = iconoXatGrupalAModificar.getImage().getScaledInstance(17, 17, Image.SCALE_SMOOTH);
        Image iconoSettingsModificat = iconoSettingAModificar.getImage().getScaledInstance(17, 17, Image.SCALE_SMOOTH);
        Image iconoEnviarModificat = iconoEnviarModificar.getImage().getScaledInstance(17, 17, Image.SCALE_SMOOTH);

        ImageIcon iconoXatPrivat = new ImageIcon(iconoXatPrivatModificat);
        ImageIcon iconoXatGrupal = new ImageIcon(iconoXatGrupalModificat);
        ImageIcon iconoSettings = new ImageIcon(iconoSettingsModificat);
        ImageIcon iconoEnviar = new ImageIcon(iconoEnviarModificat);

        this.botoXatPrivat.setIcon(iconoXatPrivat);
        this.botoXatGrupal.setIcon(iconoXatGrupal);
        this.botoSettings.setIcon(iconoSettings);
        this.botoEnviarMsg.setIcon(iconoEnviar);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterficieXatProvisional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterficieXatProvisional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterficieXatProvisional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterficieXatProvisional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterficieXatProvisional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoEnviarMsg;
    private javax.swing.JButton botoSettings;
    private javax.swing.JButton botoXatGrupal;
    private javax.swing.JButton botoXatPrivat;
    private componentsPersonalitzats.JTextFieldPersonalitzat inputMsg;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaMissatge;
    private javax.swing.JLabel textLlistatUsuarisConectats;
    // End of variables declaration//GEN-END:variables
}
