package exercicis.interficiechat;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author David Boix Sanchez i Oleh Plechiy Andriyovech Tupis
 * @version 1.0
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        inicialitzarIconos();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        vistaGeneral = new javax.swing.JPanel();
        headerVista = new javax.swing.JPanel();
        titolVista = new javax.swing.JLabel();
        mainVista = new javax.swing.JPanel();
        iconoImatge = new javax.swing.JLabel();
        footerVista = new javax.swing.JPanel();
        botoIniciSessio = new javax.swing.JButton();
        botoRegistre = new javax.swing.JButton();
        menuSeleccio1 = new javax.swing.JMenuBar();
        menuDesplegableOpcions = new javax.swing.JMenu();
        menuOpcioLogin = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuDesplegableSortir = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vista principal");

        vistaGeneral.setToolTipText("");
        vistaGeneral.setLayout(new java.awt.BorderLayout());

        headerVista.setToolTipText("");
        headerVista.setLayout(new java.awt.GridLayout());

        titolVista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titolVista.setText("PRINCIPAL");
        titolVista.setToolTipText("Titol de la vista");
        headerVista.add(titolVista);

        vistaGeneral.add(headerVista, java.awt.BorderLayout.PAGE_START);

        mainVista.setLayout(new java.awt.GridLayout());

        iconoImatge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainVista.add(iconoImatge);

        vistaGeneral.add(mainVista, java.awt.BorderLayout.CENTER);

        java.awt.GridBagLayout footerVistaLayout = new java.awt.GridBagLayout();
        footerVistaLayout.columnWidths = new int[] {0, 50, 0};
        footerVistaLayout.rowHeights = new int[] {0};
        footerVista.setLayout(footerVistaLayout);

        botoIniciSessio.setText("Login");
        botoIniciSessio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoIniciSessioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        footerVista.add(botoIniciSessio, gridBagConstraints);

        botoRegistre.setText("Registre");
        botoRegistre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoRegistreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        footerVista.add(botoRegistre, gridBagConstraints);

        vistaGeneral.add(footerVista, java.awt.BorderLayout.PAGE_END);

        menuDesplegableOpcions.setText("Opcions");

        menuOpcioLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuOpcioLogin.setText("Login");
        menuDesplegableOpcions.add(menuOpcioLogin);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Registre");
        menuDesplegableOpcions.add(jMenuItem2);

        menuSeleccio1.add(menuDesplegableOpcions);

        menuDesplegableSortir.setText("Sortir");
        menuDesplegableSortir.setToolTipText("");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Sortir");
        menuDesplegableSortir.add(jMenuItem3);

        menuSeleccio1.add(menuDesplegableSortir);

        setJMenuBar(menuSeleccio1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoIniciSessioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoIniciSessioActionPerformed
        tancarFinestra();
        Login login = new Login();
        login.setVisible(true);
        /**
         * TODO: En aquest moment ho deixarem comentat perque estem preparant la
         * interficie
         *
         */
        login.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_botoIniciSessioActionPerformed

    private void botoRegistreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoRegistreActionPerformed
        tancarFinestra();
        Registre registre = new Registre();
        registre.setVisible(true);
        /**
         * TODO: En aquest moment ho deixarem comentat perque estem preparant la
         * interficie
         *
         */
        registre.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_botoRegistreActionPerformed
    /**
     * Funcio desenvolupada per poder inicialitzar icones personalitzades un cop
     * s'inicia la aplicació .
     */
    private void inicialitzarIconos() {
//        TODO: Re
        ImageIcon logoXatAModificar = new ImageIcon("src\\main\\java\\img\\logoXat.png");
        Image logoXatModificat = logoXatAModificar.getImage().getScaledInstance(512, 512, Image.SCALE_SMOOTH);
        ImageIcon logoXat = new ImageIcon(logoXatModificat);
        this.iconoImatge.setIcon(logoXat);
    }

    /**
     * Funcio desenvolupada per poder tancar la finestra que tenim oberta en
     * aquell moment
     */
    private void tancarFinestra() {
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoIniciSessio;
    private javax.swing.JButton botoRegistre;
    private javax.swing.JPanel footerVista;
    private javax.swing.JPanel headerVista;
    private javax.swing.JLabel iconoImatge;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel mainVista;
    private javax.swing.JMenu menuDesplegableOpcions;
    private javax.swing.JMenu menuDesplegableSortir;
    private javax.swing.JMenuItem menuOpcioLogin;
    private javax.swing.JMenuBar menuSeleccio1;
    private javax.swing.JLabel titolVista;
    private javax.swing.JPanel vistaGeneral;
    // End of variables declaration//GEN-END:variables
}
